#!/bin/zsh

found=$(ag -l "$2" "_posts/$1" |head -n1)

if [[ $found ]]; then
    vim "$found"
else
    vim -c ':r _templates/post.markdown' "_posts/$1/$(date +%Y-%m-%d)-$(echo "$2" | tr " " "-").markdown"
fi
